kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: source-pvc-tekton
spec:
  storageClassName: ibmc-block-bronze
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Mi
  volumeMode: Filesystem

